### ISSUE TITLE
Will not save

### ISSUE THREAD

**Issue by Dunstrum** [nebularg/Parrot2#37] opened 2017-11-29 18:54 UTC
### What steps will reproduce the problem?
1.  Change the Direction Normal setting for Inbound and outbound.
2.  
3.  

### What version of Parrot are you using?
V2.0.10

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Every time i change how the text should scroll to Down center, and change character it loops back to what it was before. I can change where the text is but the scroll direction always change back to default.
Some time's the scroll area settings will not show up at all.

**Comment by nebularg** [comment] 2017-12-17 06:43
Duplicate of #23

**Closed by nebularg** 2017-12-17 06:43 UTC
